// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4HnWvHfK3N8D-_64WBnkti8MCOcXuqCU',
    appId: '1:638590424178:android:397a104e08e87fa9bd5eeb',
    messagingSenderId: '638590424178',
    projectId: 'food-delivery-4cfb0',
    storageBucket: 'food-delivery-4cfb0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5eivzWSgCII60FxxeY8ECTI2NzxhZjEM',
    appId: '1:638590424178:ios:218fe36741974d22bd5eeb',
    messagingSenderId: '638590424178',
    projectId: 'food-delivery-4cfb0',
    storageBucket: 'food-delivery-4cfb0.firebasestorage.app',
    androidClientId: '638590424178-d5erqt4unav0lc2qujut6m21dl5ehi72.apps.googleusercontent.com',
    iosClientId: '638590424178-d8974b0lofp511eg78afraoet1ue2s3i.apps.googleusercontent.com',
    iosBundleId: 'com.example.fooddeliveryapp',
  );
}
