// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBw_GhkBZAxgrLUBaAIzjziBFwRuO8dkO8',
    appId: '1:638590424178:web:337e25068ce1a790bd5eeb',
    messagingSenderId: '638590424178',
    projectId: 'food-delivery-4cfb0',
    authDomain: 'food-delivery-4cfb0.firebaseapp.com',
    storageBucket: 'food-delivery-4cfb0.firebasestorage.app',
    measurementId: 'G-5JQPR7GR1Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4HnWvHfK3N8D-_64WBnkti8MCOcXuqCU',
    appId: '1:638590424178:android:2aab1f852435f0fabd5eeb',
    messagingSenderId: '638590424178',
    projectId: 'food-delivery-4cfb0',
    storageBucket: 'food-delivery-4cfb0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5eivzWSgCII60FxxeY8ECTI2NzxhZjEM',
    appId: '1:638590424178:ios:f2d86f20c08bfa14bd5eeb',
    messagingSenderId: '638590424178',
    projectId: 'food-delivery-4cfb0',
    storageBucket: 'food-delivery-4cfb0.firebasestorage.app',
    iosBundleId: 'com.example.foodDeliveryApp',
  );
}
